//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.JewGymService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.JewGymService.ExerciseInWorkOut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.JewGymService.Workout))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.JewGymService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.JewGymService.WorkoutPlan))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WpfClient.JewGymService.Exercise))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExerciseInWorkOut", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class ExerciseInWorkOut : WpfClient.JewGymService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.JewGymService.Exercise ExerciseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RepsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.JewGymService.Workout WorkoutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.JewGymService.Exercise Exercise {
            get {
                return this.ExerciseField;
            }
            set {
                if ((object.ReferenceEquals(this.ExerciseField, value) != true)) {
                    this.ExerciseField = value;
                    this.RaisePropertyChanged("Exercise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Reps {
            get {
                return this.RepsField;
            }
            set {
                if ((this.RepsField.Equals(value) != true)) {
                    this.RepsField = value;
                    this.RaisePropertyChanged("Reps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sets {
            get {
                return this.SetsField;
            }
            set {
                if ((this.SetsField.Equals(value) != true)) {
                    this.SetsField = value;
                    this.RaisePropertyChanged("Sets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.JewGymService.Workout Workout {
            get {
                return this.WorkoutField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkoutField, value) != true)) {
                    this.WorkoutField = value;
                    this.RaisePropertyChanged("Workout");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Workout", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Workout : WpfClient.JewGymService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.JewGymService.ExerciseInWorkOutList ExInWorkoutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.JewGymService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.JewGymService.ExerciseInWorkOutList ExInWorkout {
            get {
                return this.ExInWorkoutField;
            }
            set {
                if ((object.ReferenceEquals(this.ExInWorkoutField, value) != true)) {
                    this.ExInWorkoutField = value;
                    this.RaisePropertyChanged("ExInWorkout");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.JewGymService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : WpfClient.JewGymService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDay {
            get {
                return this.BirthDayField;
            }
            set {
                if ((this.BirthDayField.Equals(value) != true)) {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsManager {
            get {
                return this.IsManagerField;
            }
            set {
                if ((this.IsManagerField.Equals(value) != true)) {
                    this.IsManagerField = value;
                    this.RaisePropertyChanged("IsManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkoutPlan", Namespace="http://schemas.datacontract.org/2004/07/PlanModel")]
    [System.SerializableAttribute()]
    public partial class WorkoutPlan : WpfClient.JewGymService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.JewGymService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfClient.JewGymService.Workout WorkoutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day {
            get {
                return this.DayField;
            }
            set {
                if ((this.DayField.Equals(value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.JewGymService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfClient.JewGymService.Workout Workout {
            get {
                return this.WorkoutField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkoutField, value) != true)) {
                    this.WorkoutField = value;
                    this.RaisePropertyChanged("Workout");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exercise", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Exercise : WpfClient.JewGymService.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DifficultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExerciseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExerciseUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCompoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetMuscleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Difficulty {
            get {
                return this.DifficultyField;
            }
            set {
                if ((this.DifficultyField.Equals(value) != true)) {
                    this.DifficultyField = value;
                    this.RaisePropertyChanged("Difficulty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExerciseName {
            get {
                return this.ExerciseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExerciseNameField, value) != true)) {
                    this.ExerciseNameField = value;
                    this.RaisePropertyChanged("ExerciseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExerciseUrl {
            get {
                return this.ExerciseUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ExerciseUrlField, value) != true)) {
                    this.ExerciseUrlField = value;
                    this.RaisePropertyChanged("ExerciseUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompound {
            get {
                return this.IsCompoundField;
            }
            set {
                if ((this.IsCompoundField.Equals(value) != true)) {
                    this.IsCompoundField = value;
                    this.RaisePropertyChanged("IsCompound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetMuscle {
            get {
                return this.TargetMuscleField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetMuscleField, value) != true)) {
                    this.TargetMuscleField = value;
                    this.RaisePropertyChanged("TargetMuscle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExerciseInWorkOutList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="ExerciseInWorkOut")]
    [System.SerializableAttribute()]
    public class ExerciseInWorkOutList : System.Collections.Generic.List<WpfClient.JewGymService.ExerciseInWorkOut> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExerciseList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Exercise")]
    [System.SerializableAttribute()]
    public class ExerciseList : System.Collections.Generic.List<WpfClient.JewGymService.Exercise> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="WorkoutList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Workout")]
    [System.SerializableAttribute()]
    public class WorkoutList : System.Collections.Generic.List<WpfClient.JewGymService.Workout> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="User")]
    [System.SerializableAttribute()]
    public class UserList : System.Collections.Generic.List<WpfClient.JewGymService.User> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="WorkoutPlanList", Namespace="http://schemas.datacontract.org/2004/07/PlanModel", ItemName="WorkoutPlan")]
    [System.SerializableAttribute()]
    public class WorkoutPlanList : System.Collections.Generic.List<WpfClient.JewGymService.WorkoutPlan> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JewGymService.IServiceModel")]
    public interface IServiceModel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/InsertExercises", ReplyAction="http://tempuri.org/IServiceModel/InsertExercisesResponse")]
        int InsertExercises(WpfClient.JewGymService.Exercise exercise);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/InsertExercises", ReplyAction="http://tempuri.org/IServiceModel/InsertExercisesResponse")]
        System.Threading.Tasks.Task<int> InsertExercisesAsync(WpfClient.JewGymService.Exercise exercise);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateExercises", ReplyAction="http://tempuri.org/IServiceModel/UpdateExercisesResponse")]
        int UpdateExercises(WpfClient.JewGymService.Exercise exercise);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateExercises", ReplyAction="http://tempuri.org/IServiceModel/UpdateExercisesResponse")]
        System.Threading.Tasks.Task<int> UpdateExercisesAsync(WpfClient.JewGymService.Exercise exercise);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteExercises", ReplyAction="http://tempuri.org/IServiceModel/DeleteExercisesResponse")]
        int DeleteExercises(WpfClient.JewGymService.Exercise exercise);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteExercises", ReplyAction="http://tempuri.org/IServiceModel/DeleteExercisesResponse")]
        System.Threading.Tasks.Task<int> DeleteExercisesAsync(WpfClient.JewGymService.Exercise exercise);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectAllExercises", ReplyAction="http://tempuri.org/IServiceModel/SelectAllExercisesResponse")]
        WpfClient.JewGymService.ExerciseList SelectAllExercises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectAllExercises", ReplyAction="http://tempuri.org/IServiceModel/SelectAllExercisesResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.ExerciseList> SelectAllExercisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/InsertExInWorkout", ReplyAction="http://tempuri.org/IServiceModel/InsertExInWorkoutResponse")]
        int InsertExInWorkout(WpfClient.JewGymService.ExerciseInWorkOut exinw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/InsertExInWorkout", ReplyAction="http://tempuri.org/IServiceModel/InsertExInWorkoutResponse")]
        System.Threading.Tasks.Task<int> InsertExInWorkoutAsync(WpfClient.JewGymService.ExerciseInWorkOut exinw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateExInWorkout", ReplyAction="http://tempuri.org/IServiceModel/UpdateExInWorkoutResponse")]
        int UpdateExInWorkout(WpfClient.JewGymService.ExerciseInWorkOut exinw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateExInWorkout", ReplyAction="http://tempuri.org/IServiceModel/UpdateExInWorkoutResponse")]
        System.Threading.Tasks.Task<int> UpdateExInWorkoutAsync(WpfClient.JewGymService.ExerciseInWorkOut exinw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteExInWorkout", ReplyAction="http://tempuri.org/IServiceModel/DeleteExInWorkoutResponse")]
        int DeleteExInWorkout(WpfClient.JewGymService.ExerciseInWorkOut exinw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteExInWorkout", ReplyAction="http://tempuri.org/IServiceModel/DeleteExInWorkoutResponse")]
        System.Threading.Tasks.Task<int> DeleteExInWorkoutAsync(WpfClient.JewGymService.ExerciseInWorkOut exinw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteAllExInWorkout", ReplyAction="http://tempuri.org/IServiceModel/DeleteAllExInWorkoutResponse")]
        int DeleteAllExInWorkout(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteAllExInWorkout", ReplyAction="http://tempuri.org/IServiceModel/DeleteAllExInWorkoutResponse")]
        System.Threading.Tasks.Task<int> DeleteAllExInWorkoutAsync(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectAllExercisesInWorkout", ReplyAction="http://tempuri.org/IServiceModel/SelectAllExercisesInWorkoutResponse")]
        WpfClient.JewGymService.ExerciseInWorkOutList SelectAllExercisesInWorkout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectAllExercisesInWorkout", ReplyAction="http://tempuri.org/IServiceModel/SelectAllExercisesInWorkoutResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.ExerciseInWorkOutList> SelectAllExercisesInWorkoutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectExInByWorkOut", ReplyAction="http://tempuri.org/IServiceModel/SelectExInByWorkOutResponse")]
        WpfClient.JewGymService.ExerciseInWorkOutList SelectExInByWorkOut(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectExInByWorkOut", ReplyAction="http://tempuri.org/IServiceModel/SelectExInByWorkOutResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.ExerciseInWorkOutList> SelectExInByWorkOutAsync(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/InsertWorkout", ReplyAction="http://tempuri.org/IServiceModel/InsertWorkoutResponse")]
        int InsertWorkout(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/InsertWorkout", ReplyAction="http://tempuri.org/IServiceModel/InsertWorkoutResponse")]
        System.Threading.Tasks.Task<int> InsertWorkoutAsync(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateWorkout", ReplyAction="http://tempuri.org/IServiceModel/UpdateWorkoutResponse")]
        int UpdateWorkout(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateWorkout", ReplyAction="http://tempuri.org/IServiceModel/UpdateWorkoutResponse")]
        System.Threading.Tasks.Task<int> UpdateWorkoutAsync(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteWorkout", ReplyAction="http://tempuri.org/IServiceModel/DeleteWorkoutResponse")]
        int DeleteWorkout(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteWorkout", ReplyAction="http://tempuri.org/IServiceModel/DeleteWorkoutResponse")]
        System.Threading.Tasks.Task<int> DeleteWorkoutAsync(WpfClient.JewGymService.Workout workout);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectAllWorkouts", ReplyAction="http://tempuri.org/IServiceModel/SelectAllWorkoutsResponse")]
        WpfClient.JewGymService.WorkoutList SelectAllWorkouts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectAllWorkouts", ReplyAction="http://tempuri.org/IServiceModel/SelectAllWorkoutsResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.WorkoutList> SelectAllWorkoutsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectWorkoutById", ReplyAction="http://tempuri.org/IServiceModel/SelectWorkoutByIdResponse")]
        WpfClient.JewGymService.Workout SelectWorkoutById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectWorkoutById", ReplyAction="http://tempuri.org/IServiceModel/SelectWorkoutByIdResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.Workout> SelectWorkoutByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/Login", ReplyAction="http://tempuri.org/IServiceModel/LoginResponse")]
        WpfClient.JewGymService.User Login(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/Login", ReplyAction="http://tempuri.org/IServiceModel/LoginResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.User> LoginAsync(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/NewUser", ReplyAction="http://tempuri.org/IServiceModel/NewUserResponse")]
        int NewUser(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/NewUser", ReplyAction="http://tempuri.org/IServiceModel/NewUserResponse")]
        System.Threading.Tasks.Task<int> NewUserAsync(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/IsEmailFree", ReplyAction="http://tempuri.org/IServiceModel/IsEmailFreeResponse")]
        bool IsEmailFree(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/IsEmailFree", ReplyAction="http://tempuri.org/IServiceModel/IsEmailFreeResponse")]
        System.Threading.Tasks.Task<bool> IsEmailFreeAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateUser", ReplyAction="http://tempuri.org/IServiceModel/UpdateUserResponse")]
        int UpdateUser(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateUser", ReplyAction="http://tempuri.org/IServiceModel/UpdateUserResponse")]
        System.Threading.Tasks.Task<int> UpdateUserAsync(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteUser", ReplyAction="http://tempuri.org/IServiceModel/DeleteUserResponse")]
        int DeleteUser(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteUser", ReplyAction="http://tempuri.org/IServiceModel/DeleteUserResponse")]
        System.Threading.Tasks.Task<int> DeleteUserAsync(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectAllUsers", ReplyAction="http://tempuri.org/IServiceModel/SelectAllUsersResponse")]
        WpfClient.JewGymService.UserList SelectAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/SelectAllUsers", ReplyAction="http://tempuri.org/IServiceModel/SelectAllUsersResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.UserList> SelectAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/GetAllPlanAdmins", ReplyAction="http://tempuri.org/IServiceModel/GetAllPlanAdminsResponse")]
        WpfClient.JewGymService.UserList GetAllPlanAdmins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/GetAllPlanAdmins", ReplyAction="http://tempuri.org/IServiceModel/GetAllPlanAdminsResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.UserList> GetAllPlanAdminsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/GetUserWorkoutPlans", ReplyAction="http://tempuri.org/IServiceModel/GetUserWorkoutPlansResponse")]
        WpfClient.JewGymService.WorkoutPlanList GetUserWorkoutPlans(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/GetUserWorkoutPlans", ReplyAction="http://tempuri.org/IServiceModel/GetUserWorkoutPlansResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.WorkoutPlanList> GetUserWorkoutPlansAsync(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/InsertWorkoutPlan", ReplyAction="http://tempuri.org/IServiceModel/InsertWorkoutPlanResponse")]
        int InsertWorkoutPlan(WpfClient.JewGymService.WorkoutPlan plan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/InsertWorkoutPlan", ReplyAction="http://tempuri.org/IServiceModel/InsertWorkoutPlanResponse")]
        System.Threading.Tasks.Task<int> InsertWorkoutPlanAsync(WpfClient.JewGymService.WorkoutPlan plan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateWorkoutPlan", ReplyAction="http://tempuri.org/IServiceModel/UpdateWorkoutPlanResponse")]
        int UpdateWorkoutPlan(WpfClient.JewGymService.WorkoutPlan plan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/UpdateWorkoutPlan", ReplyAction="http://tempuri.org/IServiceModel/UpdateWorkoutPlanResponse")]
        System.Threading.Tasks.Task<int> UpdateWorkoutPlanAsync(WpfClient.JewGymService.WorkoutPlan plan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteWorkoutPlan", ReplyAction="http://tempuri.org/IServiceModel/DeleteWorkoutPlanResponse")]
        int DeleteWorkoutPlan(WpfClient.JewGymService.WorkoutPlan plan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeleteWorkoutPlan", ReplyAction="http://tempuri.org/IServiceModel/DeleteWorkoutPlanResponse")]
        System.Threading.Tasks.Task<int> DeleteWorkoutPlanAsync(WpfClient.JewGymService.WorkoutPlan plan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/GetTodayWorkoutPlan", ReplyAction="http://tempuri.org/IServiceModel/GetTodayWorkoutPlanResponse")]
        WpfClient.JewGymService.WorkoutPlan GetTodayWorkoutPlan(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/GetTodayWorkoutPlan", ReplyAction="http://tempuri.org/IServiceModel/GetTodayWorkoutPlanResponse")]
        System.Threading.Tasks.Task<WpfClient.JewGymService.WorkoutPlan> GetTodayWorkoutPlanAsync(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeletePlansByUser", ReplyAction="http://tempuri.org/IServiceModel/DeletePlansByUserResponse")]
        int DeletePlansByUser(WpfClient.JewGymService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceModel/DeletePlansByUser", ReplyAction="http://tempuri.org/IServiceModel/DeletePlansByUserResponse")]
        System.Threading.Tasks.Task<int> DeletePlansByUserAsync(WpfClient.JewGymService.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceModelChannel : WpfClient.JewGymService.IServiceModel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceModelClient : System.ServiceModel.ClientBase<WpfClient.JewGymService.IServiceModel>, WpfClient.JewGymService.IServiceModel {
        
        public ServiceModelClient() {
        }
        
        public ServiceModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertExercises(WpfClient.JewGymService.Exercise exercise) {
            return base.Channel.InsertExercises(exercise);
        }
        
        public System.Threading.Tasks.Task<int> InsertExercisesAsync(WpfClient.JewGymService.Exercise exercise) {
            return base.Channel.InsertExercisesAsync(exercise);
        }
        
        public int UpdateExercises(WpfClient.JewGymService.Exercise exercise) {
            return base.Channel.UpdateExercises(exercise);
        }
        
        public System.Threading.Tasks.Task<int> UpdateExercisesAsync(WpfClient.JewGymService.Exercise exercise) {
            return base.Channel.UpdateExercisesAsync(exercise);
        }
        
        public int DeleteExercises(WpfClient.JewGymService.Exercise exercise) {
            return base.Channel.DeleteExercises(exercise);
        }
        
        public System.Threading.Tasks.Task<int> DeleteExercisesAsync(WpfClient.JewGymService.Exercise exercise) {
            return base.Channel.DeleteExercisesAsync(exercise);
        }
        
        public WpfClient.JewGymService.ExerciseList SelectAllExercises() {
            return base.Channel.SelectAllExercises();
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.ExerciseList> SelectAllExercisesAsync() {
            return base.Channel.SelectAllExercisesAsync();
        }
        
        public int InsertExInWorkout(WpfClient.JewGymService.ExerciseInWorkOut exinw) {
            return base.Channel.InsertExInWorkout(exinw);
        }
        
        public System.Threading.Tasks.Task<int> InsertExInWorkoutAsync(WpfClient.JewGymService.ExerciseInWorkOut exinw) {
            return base.Channel.InsertExInWorkoutAsync(exinw);
        }
        
        public int UpdateExInWorkout(WpfClient.JewGymService.ExerciseInWorkOut exinw) {
            return base.Channel.UpdateExInWorkout(exinw);
        }
        
        public System.Threading.Tasks.Task<int> UpdateExInWorkoutAsync(WpfClient.JewGymService.ExerciseInWorkOut exinw) {
            return base.Channel.UpdateExInWorkoutAsync(exinw);
        }
        
        public int DeleteExInWorkout(WpfClient.JewGymService.ExerciseInWorkOut exinw) {
            return base.Channel.DeleteExInWorkout(exinw);
        }
        
        public System.Threading.Tasks.Task<int> DeleteExInWorkoutAsync(WpfClient.JewGymService.ExerciseInWorkOut exinw) {
            return base.Channel.DeleteExInWorkoutAsync(exinw);
        }
        
        public int DeleteAllExInWorkout(WpfClient.JewGymService.Workout workout) {
            return base.Channel.DeleteAllExInWorkout(workout);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAllExInWorkoutAsync(WpfClient.JewGymService.Workout workout) {
            return base.Channel.DeleteAllExInWorkoutAsync(workout);
        }
        
        public WpfClient.JewGymService.ExerciseInWorkOutList SelectAllExercisesInWorkout() {
            return base.Channel.SelectAllExercisesInWorkout();
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.ExerciseInWorkOutList> SelectAllExercisesInWorkoutAsync() {
            return base.Channel.SelectAllExercisesInWorkoutAsync();
        }
        
        public WpfClient.JewGymService.ExerciseInWorkOutList SelectExInByWorkOut(WpfClient.JewGymService.Workout workout) {
            return base.Channel.SelectExInByWorkOut(workout);
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.ExerciseInWorkOutList> SelectExInByWorkOutAsync(WpfClient.JewGymService.Workout workout) {
            return base.Channel.SelectExInByWorkOutAsync(workout);
        }
        
        public int InsertWorkout(WpfClient.JewGymService.Workout workout) {
            return base.Channel.InsertWorkout(workout);
        }
        
        public System.Threading.Tasks.Task<int> InsertWorkoutAsync(WpfClient.JewGymService.Workout workout) {
            return base.Channel.InsertWorkoutAsync(workout);
        }
        
        public int UpdateWorkout(WpfClient.JewGymService.Workout workout) {
            return base.Channel.UpdateWorkout(workout);
        }
        
        public System.Threading.Tasks.Task<int> UpdateWorkoutAsync(WpfClient.JewGymService.Workout workout) {
            return base.Channel.UpdateWorkoutAsync(workout);
        }
        
        public int DeleteWorkout(WpfClient.JewGymService.Workout workout) {
            return base.Channel.DeleteWorkout(workout);
        }
        
        public System.Threading.Tasks.Task<int> DeleteWorkoutAsync(WpfClient.JewGymService.Workout workout) {
            return base.Channel.DeleteWorkoutAsync(workout);
        }
        
        public WpfClient.JewGymService.WorkoutList SelectAllWorkouts() {
            return base.Channel.SelectAllWorkouts();
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.WorkoutList> SelectAllWorkoutsAsync() {
            return base.Channel.SelectAllWorkoutsAsync();
        }
        
        public WpfClient.JewGymService.Workout SelectWorkoutById(int id) {
            return base.Channel.SelectWorkoutById(id);
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.Workout> SelectWorkoutByIdAsync(int id) {
            return base.Channel.SelectWorkoutByIdAsync(id);
        }
        
        public WpfClient.JewGymService.User Login(WpfClient.JewGymService.User user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.User> LoginAsync(WpfClient.JewGymService.User user) {
            return base.Channel.LoginAsync(user);
        }
        
        public int NewUser(WpfClient.JewGymService.User user) {
            return base.Channel.NewUser(user);
        }
        
        public System.Threading.Tasks.Task<int> NewUserAsync(WpfClient.JewGymService.User user) {
            return base.Channel.NewUserAsync(user);
        }
        
        public bool IsEmailFree(string email) {
            return base.Channel.IsEmailFree(email);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmailFreeAsync(string email) {
            return base.Channel.IsEmailFreeAsync(email);
        }
        
        public int UpdateUser(WpfClient.JewGymService.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserAsync(WpfClient.JewGymService.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public int DeleteUser(WpfClient.JewGymService.User user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAsync(WpfClient.JewGymService.User user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public WpfClient.JewGymService.UserList SelectAllUsers() {
            return base.Channel.SelectAllUsers();
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.UserList> SelectAllUsersAsync() {
            return base.Channel.SelectAllUsersAsync();
        }
        
        public WpfClient.JewGymService.UserList GetAllPlanAdmins() {
            return base.Channel.GetAllPlanAdmins();
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.UserList> GetAllPlanAdminsAsync() {
            return base.Channel.GetAllPlanAdminsAsync();
        }
        
        public WpfClient.JewGymService.WorkoutPlanList GetUserWorkoutPlans(WpfClient.JewGymService.User user) {
            return base.Channel.GetUserWorkoutPlans(user);
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.WorkoutPlanList> GetUserWorkoutPlansAsync(WpfClient.JewGymService.User user) {
            return base.Channel.GetUserWorkoutPlansAsync(user);
        }
        
        public int InsertWorkoutPlan(WpfClient.JewGymService.WorkoutPlan plan) {
            return base.Channel.InsertWorkoutPlan(plan);
        }
        
        public System.Threading.Tasks.Task<int> InsertWorkoutPlanAsync(WpfClient.JewGymService.WorkoutPlan plan) {
            return base.Channel.InsertWorkoutPlanAsync(plan);
        }
        
        public int UpdateWorkoutPlan(WpfClient.JewGymService.WorkoutPlan plan) {
            return base.Channel.UpdateWorkoutPlan(plan);
        }
        
        public System.Threading.Tasks.Task<int> UpdateWorkoutPlanAsync(WpfClient.JewGymService.WorkoutPlan plan) {
            return base.Channel.UpdateWorkoutPlanAsync(plan);
        }
        
        public int DeleteWorkoutPlan(WpfClient.JewGymService.WorkoutPlan plan) {
            return base.Channel.DeleteWorkoutPlan(plan);
        }
        
        public System.Threading.Tasks.Task<int> DeleteWorkoutPlanAsync(WpfClient.JewGymService.WorkoutPlan plan) {
            return base.Channel.DeleteWorkoutPlanAsync(plan);
        }
        
        public WpfClient.JewGymService.WorkoutPlan GetTodayWorkoutPlan(WpfClient.JewGymService.User user) {
            return base.Channel.GetTodayWorkoutPlan(user);
        }
        
        public System.Threading.Tasks.Task<WpfClient.JewGymService.WorkoutPlan> GetTodayWorkoutPlanAsync(WpfClient.JewGymService.User user) {
            return base.Channel.GetTodayWorkoutPlanAsync(user);
        }
        
        public int DeletePlansByUser(WpfClient.JewGymService.User user) {
            return base.Channel.DeletePlansByUser(user);
        }
        
        public System.Threading.Tasks.Task<int> DeletePlansByUserAsync(WpfClient.JewGymService.User user) {
            return base.Channel.DeletePlansByUserAsync(user);
        }
    }
}
